apiVersion: v1
kind: Service
metadata:
  name: smtp 
  labels:
    app: smtp 
spec:
  ports:
  - nodePort: 30050
    port: 25
    protocol: TCP
    targetPort: 25
  selector:
    app: smtp
  type: NodePort
